### ISSUE TITLE
How to install the SVG Viewer

### ISSUE THREAD

**Issue by agaget** [slacmshankar/svg_viewer#1]
Hey, 
Great work on the archiver ! 
We are trying to access to our datas from the web, instead developping our own tool we would want to try the SVG viewer, but without manual I'm not able to launch it. How to install it please ?

**Comment by slacmshankar** [comment]
This is shipped as part of the appliance; so you should be able to look at it using the QuickChart button on the viewer.


  1.  ?Type a PV name in the UI and click on "Check Status" and click on the "Quick chart" button

I also maintain separate deployments of the SVG viewer so that I can turn around changes at a more rapid pace than the server. For this


  1.  ?I "git clone" the repo into a folder on a web server, for example, /var/www/html/svg_viewer
  2.  I have to make sure that this code in archViewer.js is satisfied
// This is one of the integration points with the server.
// This should default to a path relative location that works from the appliance UI.
// To develop/debug, override this to a absolute URL of the server with the data you are going to use for debugging/developing.
viewerVars.serverURL = "../../data";
  3.  We use Apache for load balancing the appliance; so I do this by adding these two lines to httpd.conf
    Alias "/archiveviewer/retrieval/ui/viewer" "/var/www/html/svg_viewer"
    ProxyPassMatch "^/archiveviewer/retrieval/(data|bpl)/(.+)" balancer://archiver/$1/$2
  4.  So, the viewer is accessible using http://webserver/archiveviewer/retrieval/ui/viewer/archViewer.html
  5.  When the viewer makes a call to get data, it is going to make a call to ../../data/getData.qw?pv=.... etc
  6.  This translates to http://webserver/archiveviewer/retrieval/data/getData.qw which is satisfied by the ProxyPassMatch line which routes it to the appliance.


Hope that helps a little. Please let me know if these instructions helped and I'll add them to the documentation/README.



Regards,

Murali




________________________________

**Comment by agaget** [comment]
I will check that as soon as I can and i'll keep you in touch.

Thanks a lot for your reactivity,

Alexis

**Comment by agaget** [comment]
Hi Murali,
It works perfectly, 
I just have to look for my data url (http://server_url:17668/retrieval/data) it can maybe add as an example in the README.
Otherwise it was exactly what i was looking for !

Thanks a lot

Regards
Alexis

**Comment by slacmshankar** [comment]
?Excellent. I'll add this to the documentation.


Please let me know if you run into any issues..


Regards,

Murali

________________________________
